create table public."CriminalCases" (
  id bigint generated by default as identity not null,
  date timestamp with time zone not null default now(),
  "CaseOverview" text null,
  "Evidence" text null,
  "LegalProcess" text null,
  "Updates" text null,
  constraint CriminalCases_pkey primary key (id)
) TABLESPACE pg_default;